[package]
name = "derusting"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[lints.clippy]
# large_stack_frames = "warn"

[dependencies]
const_format = "0.2"
cortex-m = {
  version = "0.7",
  features = ["critical-section-single-core"]
}
critical-section = "1"
embassy-executor = {
  version = "0.10",
  features = ["embassy-time-driver"]
}
embassy-futures = "0.1"
embassy-sync = "0.8"
embassy-time-queue-utils = "0.3"
embassy-time-driver = "0.2"
embassy-time = {
  version = "0.5",
  features = ["tick-hz-1_000", "generic-queue-32"]
}
embedded-io = "0.7"
getrandom = {
  version = "0.4",
  default-features = false
}
heapless = {
  version = "0.9",
  features = ["serde"]
}
uuid = {
  version = "1",
  default-features = false,
  features = ["serde", "v7"]
}
postcard = {
  version = "1",
  default-features = false,
}
static_cell = "2"
serde = {
  version = "1",
  default-features = false,
  features = ["derive"]
}
thiserror = {
  version = "2",
  default-features = false
}
